network:
  version: 2
  renderer: networkd
  ethernets:
    # ens33 (enp2s1) — DMZ network (VMnet3) — primary interface
    ens33:
      addresses:
        - 192.168.20.10/24
      routes:
        - to: default
          via: 192.168.20.1
          metric: 20100
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
